Web/Models/ViewModels/KnowledgeViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Web.Models.EntityModel;

namespace Web.Models.ViewModels
{
    public class KnowledgeViewModel : BaseViewModel
    {
        public knowledge_page KnowledgePage_ViewModel { get; set; }

        public List<knowledge_data> KnowledgeData_ListViewModel { get; set; }

        public IPagedList<knowledge_data> KnowledgeData_PagedListViewModel { get; set; }

        public List<knowledge_catalog> KnowledgeCatalog_ListViewModel { get; set; }

        public IPagedList<knowledge_catalog> KnowledgeCatalog_PagedListViewModel { get; set; }

        public List<knowledge_lifestyle> KnowledgeLifestyle_ListViewModel { get; set; }

        public IPagedList<knowledge_lifestyle> KnowledgeLifestyle_PagedListViewModel { get; set; }

        public knowledge_lifestyle KnowledgeLifestyle_ViewModel { get; set; }

        public knowledge_lifestyle KnowledgeLifestyle_NextViewModel { get; set; }

        public knowledge_lifestyle KnowledgeLifestyle_PrevViewModel { get; set; }
    }
}

Web/Controllers/KnowledgeController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models.Repository;
using Web.Models.ViewModels;
using Web.Service;

namespace Web.Controllers
{
    public class KnowledgeController : BaseController
    {
        //常見問題
        public ActionResult Faq(int? page)
        {
            //Language
            string lang = CultureHelper.GetLanguage();
            string langcode = CultureHelper.GetUrlLanguage();

            //Model
            KnowledgeViewModel Model = new KnowledgeViewModel();
            PageBannerService PageBanner = new PageBannerService();
            KnowledgePageService KnowledgePage = new KnowledgePageService();
            KnowledgeDataService KnowledgeData = new KnowledgeDataService();

            //Content
            Model.PageBanner_ViewModel = PageBanner.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.category == "Knowledge_Faq").SingleOrDefault();
            Model.KnowledgePage_ViewModel = KnowledgePage.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y").SingleOrDefault();
            Model.KnowledgeData_ListViewModel = KnowledgeData.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y").OrderBy(x => x.sortIndex).ThenByDescending(x => x.create_date).ToList();

            if (Model.KnowledgeData_ListViewModel != null && Model.KnowledgeData_ListViewModel.Count != 0)
            {
                var pageNumber = page ?? 1;
                var pageSize = 10;
                Model.KnowledgeData_PagedListViewModel = Model.KnowledgeData_ListViewModel.ToPagedList(pageNumber, pageSize);
                int Allpage = Convert.ToInt16(Math.Ceiling((double)Model.KnowledgeData_ListViewModel.Count / pageSize));
                ViewBag.pageView = FunctionService.getPageNum(Url.Content("~/") + langcode + "/Knowledge/Faq?", Allpage, pageNumber, Model.KnowledgeData_ListViewModel.Count, "");
            }

            //Other
            ViewBag.LayoutID = "knowledge";
            if (lang == "en")
            {
                ViewBag.ViewTitle = "FAQs  | ";
            }
            else
            {
                ViewBag.ViewTitle = "常見問題  | ";
            }

            return View(Model);
        }

        //萊禮知識庫
        public ActionResult Lifestyle(int? page)
        {
            //Language
            string lang = CultureHelper.GetLanguage();
            string langcode = CultureHelper.GetUrlLanguage();

            //Model
            KnowledgeViewModel Model = new KnowledgeViewModel();
            PageBannerService PageBanner = new PageBannerService();
            KnowledgeLifeStyleService KnowledgeLifeStyle = new KnowledgeLifeStyleService();

            //Content
            Model.PageBanner_ViewModel = PageBanner.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.category == "Knowledge_Lifestyle").SingleOrDefault();
            Model.KnowledgeLifestyle_ListViewModel = KnowledgeLifeStyle.GetAllData_KnowledgeLifestyle(lang);

            if (Model.KnowledgeLifestyle_ListViewModel != null && Model.KnowledgeLifestyle_ListViewModel.Count != 0)
            {
                var pageNumber = page ?? 1;
                var pageSize = 5;
                Model.KnowledgeLifestyle_PagedListViewModel = Model.KnowledgeLifestyle_ListViewModel.ToPagedList(pageNumber, pageSize);
                int Allpage = Convert.ToInt16(Math.Ceiling((double)Model.KnowledgeLifestyle_ListViewModel.Count / pageSize));
                ViewBag.pageView = FunctionService.getPageNum(Url.Content("~/") + langcode + "/Knowledge/Lifestyle?", Allpage, pageNumber, Model.KnowledgeLifestyle_PagedListViewModel.Count, "");
            }

            //Other
            ViewBag.LayoutID = "knowledge";
            if (lang == "en")
            {
                ViewBag.ViewTitle = "Tips of R&R  | ";
            }
            else
            {
                ViewBag.ViewTitle = "萊禮知識庫  | ";
            }
            return View(Model);
        }

        public ActionResult LifestyleData(string guid)
        {
            try
            {
                //Language
                string lang = CultureHelper.GetLanguage();

                //Model
                KnowledgeViewModel Model = new KnowledgeViewModel();
                KnowledgeLifeStyleService KnowledgeLifeStyle = new KnowledgeLifeStyleService();

                //Content
                Model.KnowledgeLifestyle_ViewModel = KnowledgeLifeStyle.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.guid == guid).SingleOrDefault();
                var NextPrev = KnowledgeLifeStyle.GetNextPrev(lang, Model.KnowledgeLifestyle_ViewModel.guid);
                Model.KnowledgeLifestyle_NextViewModel = NextPrev["Next"];
                Model.KnowledgeLifestyle_PrevViewModel = NextPrev["Prev"];

                //Other
                ViewBag.LayoutID = "knowledge";
                ViewBag.ViewTitle = Model.KnowledgeLifestyle_ViewModel.title + " | ";
                return View(Model);
            }
            catch
            {
                return RedirectToAction("List");
            }
        }
    }
}

Web/Views/Knowledge/Faq.cshtml
@using Web.Service
@model Web.Models.ViewModels.KnowledgeViewModel

<main class="l-wp-main main">
    <!-- banner section -->
    <div class="banner-section m-bn m-bn--inside">
        <div class="m-bn__ctr content">
            @if (Model.PageBanner_ViewModel != null)
            {
                <div class="m-bn__pic" data-aos="zoom-out" data-aos-duration="1500">
                    <figure data-img="full">
                        <img src="@(!string.IsNullOrEmpty(Model.PageBanner_ViewModel.pic) ? Url.Content("~" + Model.PageBanner_ViewModel.pic) : "")" alt="@Model.PageBanner_ViewModel.pic_alt">
                    </figure>
                </div>
            }
            <div class="m-bn__info">
                @if (Model.PageBanner_ViewModel != null)
                {
                    @Html.Raw(FunctionService.FormatImagePath(Model.PageBanner_ViewModel.content))
                }
                <div class="cms-tages">
                    <div class="cms-tages__toggle">
                        <div class="cms-tages__toggle-name">@Web.Resource.Resource.常見問題</div>
                        <div class="cms-tages__toggle-icon" data-icon="menu"></div>
                    </div>
                    <div class="cms-tages__ctr">
                        <ul class="cms-tages__list">
                            <li class="cms-tages__item"><a href="@Url.Action("Lifestyle", "Knowledge")" class="cms-tages__link">@Web.Resource.Resource.萊禮知識庫</a></li>
                            <li class="cms-tages__item"><a href="@Url.Action("Faq", "Knowledge")" class="cms-tages__link active">@Web.Resource.Resource.常見問題</a></li>
                            @*<li class="cms-tages__item"><a href="@Url.Action("Catalog", "Knowledge")" class="cms-tages__link">@Web.Resource.Resource.產品型錄</a></li>*@
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- faq section -->
    <div class="faq-stn">
        <h1 class="cms-headline" data-aos="fade-up">@Web.Resource.Resource.常見問題</h1>

        <div class="l-wp-1400">
            <div class="faq-ctr">
                <div class="faq-info">
                    <h2 class="faq-info__title">@Model.KnowledgePage_ViewModel.title</h2>
                    @Html.Raw(FunctionService.FormatImagePath(Model.KnowledgePage_ViewModel.content))
                </div>
                <div class="faq-list">
                    <ul class="faq-list__ul">
                        @{
                            var num = 1;
                        }
                        @foreach (var item in Model.KnowledgeData_PagedListViewModel)
                        {
                            <li class="faq-list__li">
                                <div class="faq-card">
                                    <div class="faq-card__question">
                                        <div class="faq-card__number">@num.</div>
                                        <h3 class="faq-card__name">@item.title</h3>
                                        <div class="faq-card__icon"></div>
                                    </div>
                                    <div class="faq-card__answer">
                                        @Html.Raw(FunctionService.FormatImagePath(item.content))
                                    </div>
                                </div>
                            </li>
                            num++;
                        }
                    </ul>

                    <nav class="pagination" data-aos="zoom-in">
                        <ul class="pagination__list">
                            @if (ViewBag.pageView != null)
                            {
                                @Html.Raw(FunctionService.FormatImagePath(ViewBag.pageView));
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</main>

Web/Views/Knowledge/Lifestyle.cshtml
@using Web.Service
@model Web.Models.ViewModels.KnowledgeViewModel
<main class="l-wp-main main">
    <!-- banner section -->
    <div class="banner-section m-bn m-bn--inside">
        <div class="m-bn__ctr content">
            @if (Model.PageBanner_ViewModel != null)
            {
                <div class="m-bn__pic" data-aos="zoom-out" data-aos-duration="1500">
                    <figure data-img="full">
                        <img src="@(!string.IsNullOrEmpty(Model.PageBanner_ViewModel.pic) ? Url.Content("~" + Model.PageBanner_ViewModel.pic) : "")" alt="@Model.PageBanner_ViewModel.pic_alt">
                    </figure>
                </div>
            }
            <div class="m-bn__info">
                @if (Model.PageBanner_ViewModel != null)
                {
                    @Html.Raw(FunctionService.FormatImagePath(Model.PageBanner_ViewModel.content))
                }
                <div class="cms-tages">
                    <div class="cms-tages__toggle">
                        <div class="cms-tages__toggle-name">@Web.Resource.Resource.萊禮知識庫</div>
                        <div class="cms-tages__toggle-icon" data-icon="menu"></div>
                    </div>
                    <div class="cms-tages__ctr">
                        <ul class="cms-tages__list">
                            <li class="cms-tages__item"><a href="@Url.Action("Lifestyle", "Knowledge")" class="cms-tages__link active">@Web.Resource.Resource.萊禮知識庫</a></li>
                            <li class="cms-tages__item"><a href="@Url.Action("Faq", "Knowledge")" class="cms-tages__link">@Web.Resource.Resource.常見問題</a></li>
                            @*<li class="cms-tages__item"><a href="@Url.Action("Catalog", "Knowledge")" class="cms-tages__link">@Web.Resource.Resource.產品型錄</a></li>*@
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- lifestyle section -->
    <div class="lfs-stn">
        <div class="lfs-stn__wp l-wp-1740">
            <h1 class="cms-headline cms-headline--horizontal-line" data-aos="fade-up">
                <span class="cms-headline__main">@Web.Resource.Resource.萊禮知識庫</span>
                <span class="cms-headline__sub">
                    <span class="cms-headline__sub-name">Care of your Healthy Living</span>
                </span>
            </h1>

            <div class="lfs-ctr">
                @foreach (var item in Model.KnowledgeLifestyle_PagedListViewModel.Take(1))
                {
                    <div class="lfs-main">
                        <div class="m-card m-card--lfs-main" data-href="@Url.Action("LifestyleData", "Knowledge", new { guid = item.guid})">
                            <div class="m-card__pic">
                                <div data-imgfix="in">
                                    <img src="@(!string.IsNullOrEmpty(item.pic) ? Url.Content("~" + item.pic) : "")" alt="@item.pic_alt">
                                </div>
                            </div>
                            <div class="m-card__recommend">
                                <div class="m-card__recommend-name">@Web.Resource.Resource.熱門推薦</div>
                                <div class="m-card__recommend-star">
                                    @for (var i = 1; i <= int.Parse(item.star); i++)
                                    {
                                        @Html.Raw("★");
                                    }
                                </div>
                            </div>
                            <div class="m-card__txt">
                                <div class="m-card__time">@item.startdate.Value.ToString("yyyy/MM/dd")</div>
                                <h2 class="m-card__title">@item.title</h2>
                                <div class="m-card__depiction">
                                    @Html.Raw(item.content)
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <div class="lfs-sub">
                    @foreach (var item in Model.KnowledgeLifestyle_PagedListViewModel.Skip(1))
                    {
                        <div class="m-card m-card--lfs-sub" data-href="@Url.Action("LifestyleData", "Knowledge", new { guid = item.guid})">
                            <div class="m-card__pic">
                                <div data-imgfix="in">
                                    <img src="styles/images/common/loading.gif" data-src="@(!string.IsNullOrEmpty(item.pic) ? Url.Content("~" + item.pic) : "")" alt="@item.pic_alt">
                                </div>
                            </div>
                            <div class="m-card__txt">
                                <div class="m-card__time">@item.startdate.Value.ToString("yyyy/MM/dd")</div>
                                <h2 class="m-card__title">@item.title</h2>
                                <div class="m-card__depiction">
                                    @Html.Raw(item.content)
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

        <nav class="pagination" data-aos="zoom-in">
            <ul class="pagination__list">
                @if (ViewBag.pageView != null)
                {
                    @Html.Raw(FunctionService.FormatImagePath(ViewBag.pageView));
                }
            </ul>
        </nav>
    </div>
</main>

Web/Views/Knowledge/LifestyleData.cshtml
@using Web.Service
@model Web.Models.ViewModels.KnowledgeViewModel
<main class="l-wp-main main">
    <!-- banner section -->
    <h2 class="u-visually-hidden">@Model.KnowledgeLifestyle_ViewModel.title</h2>
    <div class="banner-section m-bn m-bn--nw" data-aos="zoom-out" data-aos-duration="1500">
        <div class="m-bn__ctr content">
            <div class="m-bn__pic">
                <figure data-img="full">
                    <img src="@(!string.IsNullOrEmpty(Model.KnowledgeLifestyle_ViewModel.banner) ? Url.Content("~" + Model.KnowledgeLifestyle_ViewModel.banner) : "")" alt="@Model.KnowledgeLifestyle_ViewModel.banner_alt">
                </figure>
            </div>
            <div class="m-bn__info">
                <div class="m-bn__info-wp l-wp-1200">
                    <div class="m-bn__time" data-aos="fade-up">
                        <div class="m-bn__date">@Model.KnowledgeLifestyle_ViewModel.startdate.Value.ToString("yyyy/MM/dd")</div>
                    </div>
                    <div class="m-bn__title" data-aos="fade-down">@Model.KnowledgeLifestyle_ViewModel.title</div>
                    <div class="m-bn__btn">
                        <a href="@Url.Action("Lifestyle", "Knowledge")" class="m-btn m-btn--arrow-left-white">
                            <span class="m-btn__arrow"></span>
                            <span class="m-btn__name">@Web.Resource.Resource.返回列表</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- new section -->
    <div class="nw-stn">
        <div class="nw-stn__wp l-wp-1200" data-aos="fade-up">
            <div id="editor" class="nw-stn__editor">
                @Html.Raw(FunctionService.FormatImagePath(Model.KnowledgeLifestyle_ViewModel.content))
            </div>
        </div>

        <div class="m-gp-btn u-fw-500" data-aos="zoom-in">
            @if (Model.KnowledgeLifestyle_PrevViewModel != null)
            {
                <a href="@Url.Action("LifestyleData", "Knowledge", new { guid = Model.KnowledgeLifestyle_PrevViewModel.guid})" class="m-btn m-btn--arrow-left-gray">
                    <span class="m-btn__arrow"></span>
                    <span class="m-btn__name">@Web.Resource.Resource.前一則</span>
                </a>
            }

            <a href="@Url.Action("Lifestyle", "Knowledge")" class="m-btn m-btn--cr-gray">
                <span class="m-btn__name">@Web.Resource.Resource.返回列表</span>
            </a>

            @if (Model.KnowledgeLifestyle_NextViewModel != null)
            {
                <a href="@Url.Action("LifestyleData", "Knowledge", new { guid = Model.KnowledgeLifestyle_NextViewModel.guid})" class="m-btn m-btn--arrow-right-gray">
                    <span class="m-btn__name">@Web.Resource.Resource.下一則</span>
                    <span class="m-btn__arrow"></span>
                </a>
            }
        </div>
    </div>
</main>