Web/Models/EntityModel/about.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Web.Models.EntityModel
{
    public class about
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(64)]
        public string guid { get; set; }

        public string title { get; set; }

        [Column(TypeName = "ntext")]
        public string content_1 { get; set; }

        [Column(TypeName = "ntext")]
        public string content_2 { get; set; }

        [Column(TypeName = "ntext")]
        public string content_3 { get; set; }

        [Column(TypeName = "ntext")]
        public string content_4 { get; set; }

        [StringLength(1)]
        public string status { get; set; }

        public DateTime? create_date { get; set; }

        public DateTime? modifydate { get; set; }

        [StringLength(30)]
        public string lang { get; set; }
    }
}

Web/Models/EntityModel/certificate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Web.Models.EntityModel
{
    public class certificate
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(64)]
        public string guid { get; set; }

        public string title { get; set; }

        public string pic { get; set; }

        public string pic_alt { get; set; }

        public string bpic { get; set; }

        public string bpic_alt { get; set; }

        public int? sortIndex { get; set; }

        [StringLength(1)]
        public string status { get; set; }

        public DateTime? create_date { get; set; }

        public DateTime? modifydate { get; set; }

        [StringLength(30)]
        public string lang { get; set; }
    }
}

Web/Models/ViewModels/AboutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Web.Models.EntityModel;

namespace Web.Models.ViewModels
{
    public class AboutViewModel : BaseViewModel
    {
        public about About_ViewModel { get; set; }

        public List<course> Course_ListViewModel { get; set; }

        public List<certificate> Certificate_ListViewModel { get; set; }
    }
}

Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models.Repository;
using Web.Models.ViewModels;

namespace Web.Controllers
{
    public class AboutController : BaseController
    {
        //公司簡介
        public ActionResult Index()
        {
            //Language
            string lang = CultureHelper.GetLanguage();

            //Model
            AboutViewModel Model = new AboutViewModel();
            PageBannerService PageBanner = new PageBannerService();
            AboutService About = new AboutService();
            CourseService Curse = new CourseService();

            //Content
            Model.PageBanner_ViewModel = PageBanner.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.category == "About_Index").SingleOrDefault();
            Model.About_ViewModel = About.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y").SingleOrDefault();
            Model.Course_ListViewModel = Curse.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y").OrderBy(x => x.sortIndex).ThenByDescending(x => x.create_date).ToList();

            //Other
            ViewBag.LayoutID = "about";

            if (lang == "en")
            {
                ViewBag.ViewTitle = "Company Profile | ";
            }
            else
            {
                ViewBag.ViewTitle = "公司簡介 | ";
            }

            return View(Model);
        }

        //專業認證
        public ActionResult Certificate()
        {
            //Language
            string lang = CultureHelper.GetLanguage();

            //Model
            AboutViewModel Model = new AboutViewModel();
            PageBannerService PageBanner = new PageBannerService();
            CertficateService Certificate = new CertficateService();

            //Content
            Model.PageBanner_ViewModel = PageBanner.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.category == "About_Certificate").SingleOrDefault();
            Model.Certificate_ListViewModel = Certificate.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y").OrderBy(x => x.sortIndex).ToList();

            //Other
            ViewBag.LayoutID = "about";

            if (lang == "en")
            {
                ViewBag.ViewTitle = "Certification | ";
            }
            else
            {
                ViewBag.ViewTitle = "專業認證 | ";
            }

            return View(Model);
        }

        [HttpPost]
        public ActionResult GetPic(string guid)
        {
            try
            {
                //Language
                string lang = CultureHelper.GetLanguage();

                //Model
                CertficateService Certificate = new CertficateService();

                //Content
                var data = Certificate.GetDataPicByGuid(lang, guid);

                return Json(new { pic = data["pic"], picalt = data["pic_alt"] }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { pic = "", picalt = "" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Web/Views/About/Certificate.cshtml
@using Web.Service
@model Web.Models.ViewModels.AboutViewModel
<main class="l-wp-main main">
    <!-- banner section -->
    <div class="banner-section m-bn m-bn--inside">
        <div class="m-bn__ctr content">
            @if (Model.PageBanner_ViewModel != null)
            {
                <div class="m-bn__pic" data-aos="zoom-out" data-aos-duration="1500">
                    <figure data-img="full">
                        <img src="@(!string.IsNullOrEmpty(Model.PageBanner_ViewModel.pic) ? Url.Content("~" + Model.PageBanner_ViewModel.pic) : "")" alt="@Model.PageBanner_ViewModel.pic_alt">
                    </figure>
                </div>
            }
            <div class="m-bn__info">
                @if (Model.PageBanner_ViewModel != null)
                {
                    @Html.Raw(FunctionService.FormatImagePath(Model.PageBanner_ViewModel.content))
                }
                <div class="cms-tages">
                    <div class="cms-tages__toggle">
                        <div class="cms-tages__toggle-name">@Web.Resource.Resource.專業認證</div>
                        <div class="cms-tages__toggle-icon" data-icon="menu"></div>
                    </div>
                    <div class="cms-tages__ctr">
                        <ul class="cms-tages__list">
                            <li class="cms-tages__item"><a href="@Url.Action("Index", "About")" class="cms-tages__link">@Web.Resource.Resource.公司簡介2</a></li>
                            <li class="cms-tages__item"><a href="@Url.Action("Certificate", "About")" class="cms-tages__link active">@Web.Resource.Resource.專業認證</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- about section -->
    <div class="abt-stn">
        <div class="l-wp-1400">
            <h1 class="cms-headline cms-headline--horizontal-line" data-aos="fade-up">
                <span class="cms-headline__main">@Web.Resource.Resource.專業認證</span>
                <span class="cms-headline__sub"><span class="cms-headline__sub-name">Care of your Healthy Living</span></span>
            </h1>

            <div class="l-wp-1400">
                <ul class="catalog-list">
                    @foreach (var item in Model.Certificate_ListViewModel)
                    {
                        string[] pic = item.pic.Split(',');
                        string[] pic_alt = item.pic_alt.Split(',');

                        if (pic.Count() >= 1)
                        {
                            if (pic[0] != "" && pic[0] != null)
                            {
                                <li class="catalog-list__item" data-aos="fade-up" oncontextmenu="return false">
                                    <div class="m-card m-card--catalog">
                                        <div class="m-card__pic">
                                            <div data-imgfix="in">
                                                <img src="~/styles/images/common/loading.gif" data-src="@(!string.IsNullOrEmpty(pic[0]) ? Url.Content("~" + pic[0]) : Url.Content(""))" alt="">
                                            </div>
                                            <div class="m-card__mask">
                                                <div class="m-card__btn-lbox">
                                                    <div class="m-btn m-btn--kd-catalog js-lbox ShowPic" guid="@item.guid">
                                                        <div class="m-btn__icon" data-icon="catalog"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <h2 class="m-card__name">@item.title</h2>
                                    </div>
                                    <div class="js-lightgallery u-hide @item.guid">
                                    </div>
                                </li>
                            }

                        }
                    }
                </ul>
            </div>
        </div>
    </div>
</main>

@section scripts{
    <script>
        $(document).ready(function () {
            document.oncontextmenu = function () {
                window.event.returnValue = false;
            }
        });

        $(".ShowPic").click(function () {
            var guid = $(this).attr("guid");
            $(".js-lightgallery" + "." + guid).empty();

            $.ajax({
                url: '@Url.Action("GetPic", "About")',
                data: { guid: guid },
                type: 'POST',
                success: function (data) {
                    var pic = data.pic;
                    var alt = data.picalt;

                    var toAppend = "";
                    var num = 0;
                    $(".js-lightgallery" + "." + guid).empty();
                    $.each(pic, function (index, value) {
                        if (alt.length == 0) {
                            toAppend += '<a href="' + "../.." + value + '"><img src="' + "../.." + value + '" alt="image"></a>'
                        }
                        else {
                            toAppend += '<a href="' + "../.." + value + '"><img src="' + "../.." + value + '" alt="' + alt[num] + '"></a>'
                        }

                        num++;
                    });

                    $(".js-lightgallery" + "." + guid).append(toAppend);

                    if ($(".js-lightgallery" + "." + guid).data("lightGallery")) {
                        $(".js-lightgallery" + "." + guid).data("lightGallery").destroy(true);
                    }
                    createLightGallery(guid);
                },
                complete: function () { $(".js-lightgallery" + "." + guid).children("a").eq(0).click(); }
            });
        });

        function createLightGallery(guid) {
            $(".js-lightgallery" + "." + guid).lightGallery({
                download: false,
                fullScreen: false,
                share: false,
                actualSize: false,
                autoplayControls: false
            });
        }
    </script>
}

Web/Views/About/Index.cshtml
@using Web.Service
@model Web.Models.ViewModels.AboutViewModel
<main class="l-wp-main main">
    <!-- banner section -->
    <div class="banner-section m-bn m-bn--inside">
        <div class="m-bn__ctr content">
            @if (Model.PageBanner_ViewModel != null)
            {
                <div class="m-bn__pic" data-aos="zoom-out" data-aos-duration="1500">
                    <figure data-img="full">
                        <img src="@(!string.IsNullOrEmpty(Model.PageBanner_ViewModel.pic) ? Url.Content("~" + Model.PageBanner_ViewModel.pic) : "")" alt="@Model.PageBanner_ViewModel.pic_alt">
                    </figure>
                </div>
            }
            <div class="m-bn__info">
                @if (Model.PageBanner_ViewModel != null)
                {
                    @Html.Raw(FunctionService.FormatImagePath(Model.PageBanner_ViewModel.content))
                }

                <div class="cms-tages">
                    <div class="cms-tages__toggle">
                        <div class="cms-tages__toggle-name">@Web.Resource.Resource.公司簡介1</div>
                        <div class="cms-tages__toggle-icon" data-icon="menu"></div>
                    </div>
                    <div class="cms-tages__ctr">
                        <ul class="cms-tages__list">
                            <li class="cms-tages__item"><a href="@Url.Action("Index", "About")" class="cms-tages__link active">@Web.Resource.Resource.公司簡介2</a></li>
                            <li class="cms-tages__item"><a href="@Url.Action("Certificate", "About")" class="cms-tages__link">@Web.Resource.Resource.專業認證</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- about section -->
    <div class="abt-stn">
        <h1 class="cms-headline" data-aos="fade-up">@Web.Resource.Resource.公司簡介2</h1>
        <div class="abt-info">

            <!-- clique block -->
            @Html.Raw(FunctionService.FormatImagePath(Model.About_ViewModel.content_1))

            <!-- profession block -->
            <div class="abt-info__bk abt-info__bk--profession">
                <div class="l-wp-1380">
                    @Html.Raw(FunctionService.FormatImagePath(Model.About_ViewModel.content_2))

                    @Html.Raw(FunctionService.FormatImagePath(Model.About_ViewModel.content_3))
                </div>
            </div>

            <!-- responsibility block -->
            @Html.Raw(FunctionService.FormatImagePath(Model.About_ViewModel.content_4))

            <!-- course block -->
            <div class="abt-info__bk abt-info__bk--course">
                <div class="l-wp-1400">
                    <h2 class="abt-info__title" data-aos="fade-up">@Web.Resource.Resource.發展歷程</h2>
                    <ul class="abt-info__list">
                        @foreach (var item in Model.Course_ListViewModel)
                        {
                            <li class="abt-info__item" data-aos="fade-up">
                                <div class="abt-info__time">@item.year</div>
                                <div class="abt-info__name">@Html.Raw(FunctionService.FormatImagePath(item.content))</div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</main>