Web/Controllers/NewsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models.Repository;
using Web.Models.ViewModels;
using Web.Service;

namespace Web.Controllers
{
    public class NewsController : BaseController
    {
        //列表
        public ActionResult List(string category, int? page)
        {
            //Language
            string lang = CultureHelper.GetLanguage();
            string langcode = CultureHelper.GetUrlLanguage();

            //Model
            NewsViewModel Model = new NewsViewModel();
            PageBannerService PageBanner = new PageBannerService();
            NewsCategoryService NewsCategory = new NewsCategoryService();
            NewsService News = new NewsService();

            //Content
            Model.PageBanner_ViewModel = PageBanner.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.category == "News_List").SingleOrDefault();
            Model.NewsCategory_ListViewModel = NewsCategory.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y").OrderBy(x => x.sortIndex).ThenByDescending(x => x.create_date).ToList();

            if (!string.IsNullOrEmpty(category))
            {
                Model.NewsCategory_ViewModel = NewsCategory.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.guid == category).SingleOrDefault();
            }
            else
            {
                Model.NewsCategory_ViewModel = Model.NewsCategory_ListViewModel.FirstOrDefault();
                category = Model.NewsCategory_ViewModel.guid;
            }

            Model.News_ListViewModel = News.GetAllDataByCategory(lang, category);

            if (Model.News_ListViewModel != null && Model.News_ListViewModel.Count != 0)
            {
                var pageNumber = page ?? 1;
                var pageSize = 8;
                Model.News_PagedListViewModel = Model.News_ListViewModel.ToPagedList(pageNumber, pageSize);
                int Allpage = Convert.ToInt16(Math.Ceiling((double)Model.News_ListViewModel.Count / pageSize));
                ViewBag.pageView = FunctionService.getPageNum(Url.Content("~/") + langcode + "/News/List?category=" + category + "&", Allpage, pageNumber, Model.News_ListViewModel.Count, "");
            }

            //Other
            ViewBag.LayoutID = "news";
            ViewBag.ViewTitle = Model.NewsCategory_ViewModel.title + " | ";
            return View(Model);
        }

        //內頁
        public ActionResult Index(string guid)
        {
            try
            {
                //Language
                string lang = CultureHelper.GetLanguage();

                //Model
                NewsViewModel Model = new NewsViewModel();
                NewsService News = new NewsService();
                NewsCategoryService NewsCategory = new NewsCategoryService();

                //Content
                Model.News_ViewModel = News.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.guid == guid).SingleOrDefault();
                Model.NewsCategory_ViewModel = NewsCategory.GetAllDataByPredicate(x => x.lang == lang && x.status == "Y" && x.guid == Model.News_ViewModel.category).SingleOrDefault();

                var NextPrev = News.GetNextPrev(lang, Model.NewsCategory_ViewModel.guid, Model.News_ViewModel.guid);
                Model.News_NextViewModel = NextPrev["Next"];
                Model.News_PrevViewModel = NextPrev["Prev"];

                //Other
                ViewBag.LayoutID = "news";
                ViewBag.ViewTitle = Model.News_ViewModel.title + " | ";
                return View(Model);
            }
            catch
            {
                return RedirectToAction("List");
            }
        }
    }
}

Web/Controllers/SiteadminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Newtonsoft.Json;
using Web.Service;
using System.Collections.Specialized;
using System.Collections;
using System.Web.UI;
using Web.Repository;
using System.Configuration;
using Google.Apis.Auth.OAuth2;
using System.Data.Entity;
using System.Linq.Dynamic;
using System.Web.Script.Serialization;
using Web.ServiceModels;
using System.Web.Caching;
using Web.Models.EntityModel;
using Web.Models.Repository;

namespace Web.Controllers
{
    public class SiteadminController : Controller
    {
        public string defLang = ConfigurationManager.ConnectionStrings["defaultLanguage"].ConnectionString;

        //預設語系
        public string adminCathType = ConfigurationManager.ConnectionStrings["adminCathType"].ConnectionString;

        //後台登入記錄方式 Session or Cookie
        public string projeftNo = ConfigurationManager.ConnectionStrings["projeftNo"].ConnectionString;

        public int cacheTime = 15;

        //案件編號
        protected System.Web.Caching.Cache cacheContainer = HttpRuntime.Cache;

        private Model DB = new Model();

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public ActionResult login()
        {
            ViewBag.username = "";
            if (Request.Cookies["keepMeAccount"] != null)
            {
                HttpCookie aCookie = Request.Cookies["keepMeAccount"];

                string keepAdminID = Server.HtmlEncode(aCookie.Value.Replace("keepMeAccount=", ""));

                if (keepAdminID != null && keepAdminID != "")
                {
                    ViewBag.account = keepAdminID;
                }
            }

            bool isLogin = FunctionService.systemUserCheck();
            if (isLogin)
            {
                return RedirectPermanent(Url.Content("~/siteadmin"));
            }

            return View();
        }

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        // GET: Siteadmin
        public ActionResult Index()
        {
            bool isLogin = FunctionService.systemUserCheck();
            if (!isLogin)
            {
                return RedirectPermanent(Url.Content("~/siteadmin/login"));
            }
            if (ViewBag.permissions == null)
            {
                ViewBag.permissions = Session["permissions"];
                ViewBag.permissionsTop = Session["permissionsTop"];
            }

            ViewBag.IsGA = "Y";

            GoogleAnalyticsService GaData = new GoogleAnalyticsService();
            GaParameterModel GaParameter = new GaParameterModel();//宣告參數使用

            try
            {
                ////即時人數
                Google.Apis.Analytics.v3.Data.RealtimeData RealtimeData = GaData.nowUser();
                ViewBag.RealtimeData = RealtimeData.TotalsForAllResults["rt:pageviews"].ToString();

                GaParameter.endDate = DateTime.Now.ToString("yyyy") + "-12-31";//預設結束日
            }
            catch (Exception ex)
            {
                ViewBag.IsGA = "N";

                #region 產生LOG

                FunctionService.saveLog(ex, "Ga.txt");

                #endregion
            }
            ////總瀏覽數

            #region 總瀏覽數

            try
            {
                GaParameter.startDate = "2015-01-01";
                GaParameter.metrics = "ga:visits";
                GaParameter.Dimensions = "ga:year";
                var TotalWebView = GaData.ReGaContent(GaParameter);
                int reNum = 0;
                if (TotalWebView.Rows.Count > 0)
                {
                    foreach (List<string> item in TotalWebView.Rows)
                    {
                        reNum = reNum + int.Parse(item[1].ToString());
                    }
                }
                ViewBag.TotalWebViewNum = reNum;
            }
            catch (Exception ex)
            {
                ViewBag.IsGA = "N";

                #region 產生LOG

                FunctionService.saveLog(ex, "Ga.txt");

                #endregion
            }

            #endregion

            GaParameter.startDate = DateTime.Now.ToString("yyyy") + "-01-01";//預設起始日

            ////網站關鍵字

            #region 網站關鍵字

            try
            {
                GaParameter.metrics = "ga:organicSearches";
                GaParameter.Dimensions = "ga:keyword";
                var KeyWords = GaData.ReGaContent(GaParameter);
                ViewBag.KeyWords = KeyWords.Rows.ToList().Skip(0).Take(4);

                #endregion

                ////搜尋引勤來源數量

                #region 搜尋引勤來源數量

                GaParameter.metrics = "ga:organicSearches";
                GaParameter.Dimensions = "ga:fullReferrer";
                var FullReferrerTemp = GaData.ReGaContent(GaParameter);

                List<FullReferrerModel> FullReferrer = new List<FullReferrerModel>();
                int s = 0;
                foreach (List<string> item in FullReferrerTemp.Rows)
                {
                    FullReferrerModel m = new FullReferrerModel();
                    m.name = item[0];
                    m.num = int.Parse(item[1].ToString());
                    FullReferrer.Add(m);
                    s++;
                }
                ViewBag.FullReferrer = FullReferrer;
            }
            catch (Exception ex)
            {
                ViewBag.IsGA = "N";

                #region 產生LOG

                FunctionService.saveLog(ex, "Ga.txt");

                #endregion
            }

            #endregion

            ////本月流量次數
            try
            {
                string thisMonth = int.Parse(DateTime.Now.ToString("MM")).ToString();
                ViewBag.ViewYearUseMonth = JsonConvert.DeserializeObject(GaData.ViewYearUseMonth(thisMonth));
            }
            catch (Exception ex)
            {
                ViewBag.IsGA = "N";

                #region 產生LOG

                FunctionService.saveLog(ex, "Ga.txt");

                #endregion
            }

            // 新/舊訪問者

            #region 新舊訪問者

            try
            {
                GaParameter.metrics = "ga:users";
                GaParameter.Dimensions = "ga:userType";
                ViewBag.UserType = GaData.ReGaContent(GaParameter);
            }
            catch (Exception ex)
            {
                ViewBag.IsGA = "N";

                #region 產生LOG

                FunctionService.saveLog(ex, "Ga.txt");

                #endregion
            }

            #endregion

            //社交網站來源

            #region 社交網站來源

            try
            {
                GaParameter.metrics = "ga:organicSearches";
                GaParameter.Dimensions = "ga:socialNetwork";
                ViewBag.SocialNetwork = GaData.ReGaContent(GaParameter);

                #endregion

                //瀏覽頁面與頁面標題

                #region 瀏覽頁面與頁面標題

                GaParameter.metrics = "ga:pageviews";
                GaParameter.Dimensions = "ga:pagePath,ga:pageTitle";
                var test = GaData.ReGaContent(GaParameter);
            }
            catch (Exception ex)
            {
                // ViewBag.IsGA = "N";

                #region 產生LOG

                FunctionService.saveLog(ex, "Ga.txt");

                #endregion
            }

            #endregion

            //聯絡我們

            //ViewBag.contactData = DB.contacts.OrderByDescending(m => m.create_date).ToList().Skip(0).Take(4);

            //網址
            ViewBag.WebUrl = FunctionService.getWebUrl();

            //最新公告
            ViewBag.News = DB.news.Where(m => m.lang == defLang).OrderByDescending(m => m.startdate).ToList().Skip(0).Take(3);

            //聯絡我們
            //ViewBag.contactData = DB.contacts.OrderByDescending(m => m.create_date).ToList().Skip(0).Take(4);

            return View();
        }

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        public ActionResult list()
        {
            bool isLogin = FunctionService.systemUserCheck();
            if (!isLogin)
            {
                return RedirectPermanent(Url.Content("~/siteadmin/login"));
            }
            if (ViewBag.permissions == null)
            {
                ViewBag.permissions = Session["permissions"];
                ViewBag.permissionsTop = Session["permissionsTop"];
            }
            Session.Remove("dataTableCategory");//移除暫存細項

            ViewBag.RetuenToList = "N";
            ViewBag.statusData = null;//狀態篩選顯示
            ViewBag.statusVal = null;//狀態篩選值

            ViewBag.RetuenID = "";

            if (RouteData.Values["tables"] != null)
            {
                string tables = RouteData.Values["tables"].ToString();

                ViewBag.Tables = tables;

                ViewBag.addTitle = "";
                ViewBag.addId = "";
                Session.Remove("dataTableCategory");

                //DataTable用額外參數
                ViewBag.dataTableAddPostVal = "{'name': 'category', 'value': ''}";
                if (RouteData.Values["id"] != null)
                {
                    ViewBag.dataTableAddPostVal = "{'name': 'category', 'value': '" + RouteData.Values["id"].ToString() + "'}";

                    Session.Add("dataTableCategory", RouteData.Values["id"].ToString());//紀錄傳值

                    //取得標題

                    string reTables = ViewBag.Tables;

                    ViewBag.addTitle = TablesService.getDataTitle(reTables, RouteData.Values["id"].ToString());
                    ViewBag.addId = "?c=" + RouteData.Values["id"].ToString();
                    ViewBag.RetuenToList = "Y";
                    ViewBag.RetuenID = RouteData.Values["id"].ToString();
                }
                /*if(ViewBag.forum_status != null)
                {

Web/Views/Siteadmin/index.cshtml
@using Web.Models;
@using Web.ServiceModels;
@{
    Layout = "~/Views/Siteadmin/Shared/_Layout.cshtml";
    int i = 0;
}

<div class="content-body">

    <!-- layout-content-->
    <!-- row  -->
    <div class="row mt-xl-0 mt-3">
            <div class="col-xl-3">
                <div class="row">
                    <div class="col-sm-6 col-12 col-xl-12">
                        <section class="panel" style="min-height:205px">
                            <header class="panel-heading text-center">
                                <h2 class="h5 px-2">目前在線人數</h2>
                            </header>
                            <div class="panel-body px-0 py-0">
                                <div class="h1 text-center font-weight-bold pb-2">@if(ViewBag.IsGA == "Y"){<span class="text-primary">@ViewBag.RealtimeData</span>}</div>
                                <div class="progress" title="" style="height: 5px;">
                                    <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="row text-center py-3">
                                    <div class="col"><span class="d-block text-muted small">本月瀏覽次數</span>@if (ViewBag.IsGA == "Y")
                                    {<span class="d-block font-weight-bold mb-1">@ViewBag.ViewYearUseMonth</span>}</div>
                                    <div class="col"><span class="d-block text-muted small">本月登入帳號</span><span class="d-block font-weight-bold mb-1">---</span></div>
                                </div>
                            </div>
                        </section>
                    </div>
                    <div class="col-sm-6 col-12 col-xl-12 mt-xl-3 mt-sm-0 mt-3">
                        <section class="panel" style="min-height:205px">
                            <header class="panel-heading text-center">
                                <h2 class="h5">最新消息</h2>
                            </header>
                            @{ i = 0;}
                            @foreach (var item in ViewBag.News)
                            {
                                string vTitle = item.title;
                                if (vTitle.Length > 15)
                                {
                                    vTitle = item.title.Substring(0, 15) + "...";
                                }

                                <div class="row px-4">
                                    <div class="col text-truncate"><a class="small" target="_blank" href="@Url.Action("Index", "News", new { guid = item.guid})">@vTitle</a></div>
                                    <div class="col-auto"><span class="badge badge-pill badge-main">@DateTime.Parse(item.startdate.ToString()).ToString("yyyy-MM-dd")</span></div>
                                </div>
                                if (i < 3)
                                {
                                    <hr class="my-2 w-100">
                                }

                                i++;
                            }
                        </section>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 mt-xl-0 mt-3">
                <section class="panel">
                    <header class="panel-heading">
                        <h2 class="h5 float-left">年度數量</h2>
                        @*<button style="float:right" class="btn btn-danger" onclick="window.location.href='@Url.Content("~/siteadmin/AnalyticsInfo")';">觀看詳細統計</button>*@
                    </header>
                
                    <div class="panel-wrapper"></div>
                    <div class="panel-body pb-3">
                        <div id="analyticsAge" style="height:353px;"></div>
                    </div>
                </section>
            </div>
        </div>
    <!-- / row-->
    <!-- row    -->
   <div class="row text-center mt-3">
            <!-- col-->
            <div class="col-xl-3 col-md-6 col-sm-6">
                <section class="panel p-3 bg-main text-white">
                    <div class="row">
                        <div class="col"><span class="d-block mb-1 h3">@if (ViewBag.IsGA == "Y") {@ViewBag.SocialNetwork.Rows[0][1]}</span><span class="d-block">社群網站來源數</span></div>
                        <div class="col"><span class="icon-comment-square display-4"></span></div>
                    </div>
                </section>
            </div>
            <!-- / col-->
            <!-- col-->
            <div class="col-xl-3 col-md-6 col-sm-6">
                <section class="panel p-3 bg-warning text-white">
                    <div class="row">
                        <div class="col"><span class="d-block mb-1 h3">@if (ViewBag.IsGA == "Y") {@ViewBag.TotalWebViewNum}</span><span class="d-block">總瀏覽次數</span></div>
                        <div class="col"><span class="icon-eye4 display-4"></span></div>
                    </div>
                </section>
            </div>
            <!-- / col-->
            <!-- col-->
            <div class="col-xl-3 col-md-6 col-sm-6">
                <section class="panel p-3 bg-success text-white">
                    <div class="row">
                        <div class="col"><span class="d-block mb-1 h3">@if (ViewBag.IsGA == "Y") {@ViewBag.UserType.Rows[0][1].ToString()}</span><span class="d-block">年度新訪問者數</span></div>
                        <div class="col"><span class="icon-new-tab display-4"></span></div>
                    </div>
                </section>
            </div>
            <!-- / col-->
            <!-- col-->
            <div class="col-xl-3 col-md-6 col-sm-6">
                <section class="panel p-3 bg-primary text-white">
                    <div class="row">
                        <div class="col"><span class="d-block mb-1 h3">@if (ViewBag.IsGA == "Y") {@ViewBag.UserType.Rows[1][1].ToString()}</span><span class="d-block">年度回訪問者數</span></div>
                        <div class="col"><span class="icon-history display-4"></span></div>
                    </div>
                </section>
            </div>
            <!-- / col-->
        </div>
    <!-- / row-->
    <!-- row  -->
    <div class="row mt-3">
            <div class="col-xl-6 col-lg-12">
                <section class="panel">
                    <header class="panel-heading mb-2">
                        <h2 class="h5 float-left">搜尋引擎來源數量</h2>
                        <div class="float-right"><a class="btn btn-main btn-sm mr-15" href="forum.html" style="display:none;">瀏覽全部</a></div>
                    </header>
                    <div class="panel-wrapper">
                        <div class="panel-body" style="min-height:270px;">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="font-weight-bold">
                                        <tr>
                                            <th>No.</th>
                                            <th>來源</th>
                                            <th>數量</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (ViewBag.IsGA == "Y")
                                        {
                                            if (ViewBag.FullReferrer != null)
                                            {

                                                List<FullReferrerModel> FullReferrer = ViewBag.FullReferrer;

                                                int s = 1;
                                                foreach (FullReferrerModel item in FullReferrer.OrderByDescending(m => m.num).ToList().Skip(0).Take(4))
                                                {

                                                    <tr>
                                                        <td>@s</td>
                                                        <td>@item.name</td>
                                                        <td>@item.num</td>
                                                    </tr>
                                                    s++;
                                                }
                                            }
                                        }
                                        </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-xl-6 col-lg-12 mt-xl-0 mt-3">
                <section class="panel">
                    <header class="panel-heading mb-2">
                        <h2 class="h5 float-left">網站來源關鍵字</h2>
                        <div class="float-right"><a class="btn btn-main btn-sm mr-15" href="forum.html" style="display:none;">瀏覽全部</a></div>
                    </header>
                    <div class="panel-wrapper">
                        <div class="panel-body" style="min-height:270px;">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="font-weight-bold">
                                        <tr>
                                            <th>No.</th>
                                            <th>關鍵字</th>
                                            <th>數量</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (ViewBag.IsGA == "Y")
                                        {
                                        if (ViewBag.KeyWords != null)
                                        {
                                            int s = 1;
                                            foreach (List<string> item in ViewBag.KeyWords)
                                            {

                                                <tr>
                                                    <td>@s</td>
                                                    <td>@item[0]</td>
                                                    <td>@item[1]</td>
                                                </tr>

                                                s++;
                                            }

                                        }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    <!-- / row-->
    <!-- / layout-content-->
</div>

@section scripts {
    @if (ViewBag.IsGA == "Y")
    {
    <!--page index-->
    @Scripts.Render("~/Content/Siteadmin/scripts/index2.js")
        }
    }